FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --legacy-peer-deps
COPY . .
RUN npx nx build api --configuration=production

FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/dist/apps/api/main.js ./main.js
EXPOSE 3000
CMD ["node", "main.js"]
