name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  actions: read
  contents: read

jobs:
  commit-lint:
    name: Commit message lint
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Validate PR commit messages
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Set NX base
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "NX_BASE=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV
          else
            echo "NX_BASE=HEAD~1" >> $GITHUB_ENV
          fi

      - name: Lint affected
        run: npx nx affected --target=lint --base=$NX_BASE --head=HEAD

      - name: Test affected
        run: npx nx affected --target=test --base=$NX_BASE --head=HEAD
